# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iconblurb',
            name='icon',
            field=models.CharField(max_length=200),
        ),
    ]
