# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0002_auto_20160501_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content_content',
            field=models.TextField(default='This is it.'),
        ),
    ]
