# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
        ('sites', '0002_alter_domain_unique'),
        ('theme', '0003_homepage_content_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('featured_image', mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='Featured Image')),
                ('short_description', mezzanine.core.fields.RichTextField(blank=True)),
                ('href', models.CharField(blank=True, help_text='A link to the finished project (optional)', max_length=2000)),
            ],
            options={
                'verbose_name': 'Portfolio item',
                'ordering': ('_order',),
                'verbose_name_plural': 'Portfolio items',
            },
            bases=('pages.page', models.Model),
        ),
        migrations.CreateModel(
            name='PortfolioItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('slug', models.CharField(blank=True, help_text='Leave blank to have the URL auto-generated from the title.', max_length=2000, null=True, verbose_name='URL')),
                ('site', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'verbose_name': 'Portfolio Item Category',
                'ordering': ('title',),
                'verbose_name_plural': 'Portfolio Item Categories',
            },
        ),
        migrations.CreateModel(
            name='PortfolioItemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('file', mezzanine.core.fields.FileField(max_length=200, verbose_name='File')),
                ('portfolioitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='theme.PortfolioItem')),
            ],
            options={
                'verbose_name': 'Image',
                'ordering': ('_order',),
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.AddField(
            model_name='portfolio',
            name='columns',
            field=models.CharField(choices=[('6', 'Two columns'), ('4', 'Three columns'), ('3', 'Four columns')], default='3', max_length=1),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='content',
            field=mezzanine.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='portfolioitems', to='theme.PortfolioItemCategory', verbose_name='Categories'),
        ),
    ]
